version: "3.8"
services:
  service1:
    image: service1
    build:
      context: ./service1
    ports:
      - "5001:80"
    depends_on:
      - mongo

  service2:
    image: service2
    build:
      context: ./service2
    ports:
      - "5002:80"
    depends_on:
      - mongo

  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "5000:80"
    depends_on:
      - service1
      - service2

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: yourdb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
